### ISSUE TITLE
Histories package does not Work Please help 

### ISSUE THREAD

**Issue by mwangaben** [seancheung/history#17]
I am using Macos Mojave
-- PHP 8.0.7
-- Laravel Framework 8.46.0

$post = Post::factory()->create();

        $post->title = 'Hello world';
        $post->save();

        dd($post->histories);

returns empty array 
expect result is the past and current data of the model,  kindly tell  me if i am wrong somewhere

**Comment by seancheung** [comment]
Did you implement required traits to your model?

**Comment by smpita** [comment]
I was having a similar issue. The problem turned out to be that I was doing my testing with Tinker and it wasn't clear to me that `console_enabled` in the `history.php` config file also controlled history logging while in tinker.

Maybe update the language in the config from `When application is running in console(include seeding)` to `When application is running in console(include seeding/tinker)`
