### ISSUE TITLE
primary key

### ISSUE THREAD

**Issue by dunkel015** [seancheung/history#6]
What happens when the primary key is composed?

**Comment by seancheung** [comment]
The history table is already in a many-to-many polymorphic relation. Thus I don't think a model with compound primary key will be supported.

This won't work as you expect:
![image](https://user-images.githubusercontent.com/5442563/42921001-2dba9232-8b4c-11e8-8cc3-60ea657f0eed.png)

Due to *HistoryObserver.php*
![image](https://user-images.githubusercontent.com/5442563/42921062-6a16f3a6-8b4c-11e8-8c03-9ce0c7ff8926.png)

Compound primary keys cannot be supported by default because it's not generic(`morphMany` does support only single primary keys). You'll need to create separate history model for each tracked models and tweak something about the mechanism.
